### ISSUE TITLE
Java- Método eliminarEstudiante

### ISSUE THREAD

**Issue by JuanValladaresv2** [CodeSystem2022/ChacoDevsTeam-4SEM#1]
CREAR MÉTODO BOOLEANO eliminarEstudiante Y TESTEAR DESDE EL MAIN PREVIAMENTE CREADO EN estudianteDAO(Video 1,2)

**Comment by Renzo-Espinola** [comment]
Se comienza con el desarrollo

**Comment by Renzo-Espinola** [comment]
integrado

**Comment by JuanValladaresv2** [comment]
Prueba realizada con éxito. Se cierra el ticket.
