### ISSUE TITLE
JS- Creación carpeta de E-Commerce

### ISSUE THREAD

**Issue by JuanValladaresv2** [CodeSystem2022/ChacoDevsTeam-4SEM#10]
CREAR CARPETA e-commerce DENTRO DE ESTA CREAR LAS CARPETAS client y server, DENTRO DE LA CARPETA client CREAR media y js, 
EN LA CARPETA media CREAR UN ARCHIVO index.html Y UN ARCHIVO styles.css,EN EL ARCHIVO html VINCULAR EL ARCHIVO styles.css, EN EL BODY CREAR ETIQUEDAS DIV PARA
"card-products-container" y "card-products" (Video 1)

**Comment by Renzo-Espinola** [comment]
Se comienza el desarrollo

**Comment by Renzo-Espinola** [comment]
Integrado a develop

**Comment by JuanValladaresv2** [comment]
Prueba realizada con éxito. Se cierra el ticket.
