### ISSUE TITLE
JS-Mercado Pago

### ISSUE THREAD

**Issue by AlejoHGZ** [CodeSystem2022/ChacoDevsTeam-4SEM#104]
Integrar mercado pago desde el frontend y Crear el Botón de mercado pago( video 5 y 6 - JAVASCRIPT )  Por ultimo se requiere realizar las pruebas correspondientes videos - 7 al 10

**Comment by Federico65744** [comment]
Se comienza el desarrollo.

**Comment by Renzo-Espinola** [comment]
Se integra a develop.
