### ISSUE TITLE
JS- Archivo Index.js y Products.js

### ISSUE THREAD

**Issue by JuanValladaresv2** [CodeSystem2022/ChacoDevsTeam-4SEM#11]
CREAR EN LA CARPETA JS EL ARCHIVO index.js Y EL ARCHIVO products.js Y LLAMARLOS DESDE EL index.html (Video 2)

**Comment by NicoBalbuena** [comment]
Se inicia desarrollo

**Comment by Renzo-Espinola** [comment]
integrado a develop

**Comment by JuanValladaresv2** [comment]
Prueba realizada con éxito. Se cierra el ticket.
