### ISSUE TITLE
JAVA - Estudiante PT 2

### ISSUE THREAD

**Issue by AlejoHGZ** [CodeSystem2022/ChacoDevsTeam-4SEM#110]
Creación de la opción Eliminar estudiante y opción Salir. Hacemos pruebas (video 7 y video 8)

**Comment by ludmilailenrss** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
integrado a develop.

**Comment by AlejoHGZ** [comment]
El Testeo Fue exitoso
