### ISSUE TITLE
PYTHON - documentación de clases y métodos

### ISSUE THREAD

**Issue by Federico65744** [CodeSystem2022/ChacoDevsTeam-4SEM#125]
se requiere crear el archivo doc_str.py y la clase mi_clase.py con su métodos correspondientes y documentación(video 1).

**Comment by patiky** [comment]
inicio el desarrollo

**Comment by Renzo-Espinola** [comment]
integrado a develop.

**Comment by Federico65744** [comment]
Pruebas realizada con exito.
