### ISSUE TITLE
PYTHON-uso de __doc__ ("dunder doc")

### ISSUE THREAD

**Issue by Federico65744** [CodeSystem2022/ChacoDevsTeam-4SEM#126]
se requiere hacer uso de la función help() y __doc__ en clases y métodos para visualizar su documentación(video 2 y 3).

**Comment by TatianaGimenezRios** [comment]
Se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado a develop

**Comment by Federico65744** [comment]
pruebas realizadas con éxito.
