### ISSUE TITLE
PYTHON- String inmutables

### ISSUE THREAD

**Issue by Federico65744** [CodeSystem2022/ChacoDevsTeam-4SEM#127]
Se requiere la creación del archivo str_inmutable.py, y uso de algunos métodos para comprobar inmutabilidad de los objetos de tipo String (video 4).

**Comment by naty33** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
integrado a develop.

**Comment by Federico65744** [comment]
Prueba realizada con éxito.
