### ISSUE TITLE
PYTHON - Metodo split()

### ISSUE THREAD

**Issue by Federico65744** [CodeSystem2022/ChacoDevsTeam-4SEM#129]
se requiere crear el archivo metodo_split.py y hacer uso del método split() para separar palabras de un string y crear una lista pasándole como argumento un delimitador (**video 7 y 8**);

**Comment by DiosJuanVero2015** [comment]
Se inicia desarrollo

**Comment by Renzo-Espinola** [comment]
Integrado a develop.

**Comment by Federico65744** [comment]
Prueba realizada con éxito.
