### ISSUE TITLE
JS- Array de productos

### ISSUE THREAD

**Issue by JuanValladaresv2** [CodeSystem2022/ChacoDevsTeam-4SEM#13]
CREAR ARRAY DE PRODUCTOS EN EL ARCHIVO products.js Y CREAR UNA CONSTANTE LLAMADA shopContent EN EL ARCHIVO index.js (video 3)

**Comment by Federico65744** [comment]
Se comienza el desarrollo.

**Comment by Renzo-Espinola** [comment]
Integrado a develop.

**Comment by JuanValladaresv2** [comment]
Prueba realizada con éxito. Se cierra el ticket.
