### ISSUE TITLE
JS STACK PERN- Inicialización del proyecto

### ISSUE THREAD

**Issue by Federico65744** [CodeSystem2022/ChacoDevsTeam-4SEM#135]
se requiere crear la carpeta "PERN-stack" e Inicializar el proyecto con el comando npm init -y, luego instalar las dependencias de producción y desarrollo. (video 3 y 4)

**Comment by Renzo-Espinola** [comment]
se inicia el desarrollo.

**Comment by Renzo-Espinola** [comment]
Se crea repositorio nuevo para el stack de pern : https://github.com/CodeSystem2022/ChacoDevsTeam-ProyectoStackPern.git

**Comment by Renzo-Espinola** [comment]
integrado a develop.

**Comment by Federico65744** [comment]
Prueba realizada con éxito.
