### ISSUE TITLE
JS STACK PERN-Creación de las carpetas para backend y database

### ISSUE THREAD

**Issue by Federico65744** [CodeSystem2022/ChacoDevsTeam-4SEM#136]
se requiere crear la estructura de carpetas necesarias para el backend y crear archivos dentro de la carpeta src, luego crear la carpeta para base de datos con el archivo "init.sql" (video 5 y 6)

**Comment by JuanValladaresv2** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
Integrado en develop.

**Comment by Federico65744** [comment]
Prueba realizada con éxito.
