### ISSUE TITLE
JS STACK PERN-Creación y lanzamiento del servidor express

### ISSUE THREAD

**Issue by Federico65744** [CodeSystem2022/ChacoDevsTeam-4SEM#137]
se requiere mover las carpetas: controllers, libs, middlewares, router y schemas dentro de la carpeta "src", iniciar el servidor generar rutas de prueba y comprobar que funcionen desde el navegador. (video 7 y 8)

**Comment by NicoBalbuena** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
Integrado en develop en el repositorio de STACK PERN

**Comment by Federico65744** [comment]
Prueba realizada con éxito.
