### ISSUE TITLE
JS STACK PERN-Rutas CRUD tareas

### ISSUE THREAD

**Issue by Federico65744** [CodeSystem2022/ChacoDevsTeam-4SEM#139]
Se requiera agregar las diferentes rutas para el CRUD de tareas. (video 10)

**Comment by AlejoHGZ** [comment]
se inicia desarrollo

**Comment by Renzo-Espinola** [comment]
integrado a develop. Repositorio STACK PERN

**Comment by Federico65744** [comment]
Prueba realizada con éxito.
