### ISSUE TITLE
JAVA - Configuración y descarga del proyecto

### ISSUE THREAD

**Issue by Federico65744** [CodeSystem2022/ChacoDevsTeam-4SEM#143]
Generar el proyecto "tienda_libros" desde spring initializr con las dependencias necesarias, luego descomprimirla y ubicarla dentro de las carpetas del repositorio. (video 2)

**Comment by patiky** [comment]
inicio el desarrollo

**Comment by patiky** [comment]
desarrollo finalizado

**Comment by Renzo-Espinola** [comment]
Integrado a develop.

**Comment by Federico65744** [comment]
Prueba realizada con éxito.
