### ISSUE TITLE
JAVA - Abrir configurar y agregar logback-spring.xml

### ISSUE THREAD

**Issue by Federico65744** [CodeSystem2022/ChacoDevsTeam-4SEM#144]
Abrir el proyecto con intellij IDEA luego descargar y agregar el archivo "logback-spring.xml" dentro de la carpeta resources.(video 3 y 4)

**Comment by Ventc** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
Integrado a develop

**Comment by Federico65744** [comment]
Prueba realizada con éxito.
