### ISSUE TITLE
JAVA - Conexión a la base de datos

### ISSUE THREAD

**Issue by Federico65744** [CodeSystem2022/ChacoDevsTeam-4SEM#145]
Se requiere agregar configuración para base de datos en el archivo application.properties de la carpeta resources, luego ejecutar la aplicación para comprobar que el servidor esté funcionando. (video 5 y 6)

**Comment by JuanValladaresv2** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
integrado a develop

**Comment by Federico65744** [comment]
Prueba realizada con éxito.
