### ISSUE TITLE
NODE - Configurar variables de entorno y pruebas

### ISSUE THREAD

**Issue by Federico65744** [CodeSystem2022/ChacoDevsTeam-4SEM#146]
Se requiere: crear, darle valor y acceder a las variables de entorno **(video 1 y 2)**.

**Comment by naty33** [comment]
Commiena el desarrollo

**Comment by Renzo-Espinola** [comment]
integrado a develop

**Comment by Federico65744** [comment]
Prueba realizada con éxito.
