### ISSUE TITLE
NODE - Buenas prácticas en Node

### ISSUE THREAD

**Issue by Federico65744** [CodeSystem2022/ChacoDevsTeam-4SEM#147]
Se requiere crear la variable de entorno "WEB" y acceder desde el código **(video 3)**.

**Comment by Renzo-Espinola** [comment]
se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
integrado a develop.

**Comment by Federico65744** [comment]
Pruebas realizadas con éxito.
