### ISSUE TITLE
JAVA-Clase entidad Libro

### ISSUE THREAD

**Issue by Ventc** [CodeSystem2022/ChacoDevsTeam-4SEM#177]
VIDEO 1 = (Se requiere crear un nuevo paquete en "utn.tienda_libros" que se va a llamar "modelo" y dentro del paquete nuevo, crear una clase llamada "Libro")

**Comment by Renzo-Espinola** [comment]
se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
Integrado a develop.
