### ISSUE TITLE
JAVA-Creación de la tabla libro en la base de datos

### ISSUE THREAD

**Issue by Ventc** [CodeSystem2022/ChacoDevsTeam-4SEM#178]
VIDEO 2 = (Se requiere ejecutar el main en "TiendaLibrosApplication" para asi crear la tabla de "Libro" en el MySQL)

**Comment by ludmilailenrss** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado a develop
