### ISSUE TITLE
JAVA-Capa de Datos -> JpaRepository

### ISSUE THREAD

**Issue by Ventc** [CodeSystem2022/ChacoDevsTeam-4SEM#179]
VIDEO 3 = (Se requiere crear un nuevo paquete en "utn.tienda_libros" que se va a llamar "repositorio" y dentro del paquete nuevo, crear una interface llamada "LibroRepositorio")

**Comment by TatianaGimenezRios** [comment]
Se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
Integrado a develop
