### ISSUE TITLE
JAVA-Capa de Servicio-Parte 1 -> Interface ILibroServicio

### ISSUE THREAD

**Issue by Ventc** [CodeSystem2022/ChacoDevsTeam-4SEM#180]
VIDEO 4 = (Se requiere crear un nuevo paquete en "utn.tienda_libros" que se va a llamar "servicio" y dentro del paquete nuevo, crear una interface llamada "ILibroServicio" y una clase llamada "LibroServicio")

**Comment by NicoBalbuena** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
Integrado a develop
