### ISSUE TITLE
JAVA-Capa de Presentación -> Swing

### ISSUE THREAD

**Issue by Ventc** [CodeSystem2022/ChacoDevsTeam-4SEM#182]
VIDEO 6 = (Se requiere crear un nuevo paquete en "utn.tienda_libros" que se va a llamar "vista" y dentro del paquete nuevo, seleccionar "Swing UI Designer" y elegir ---> "GUI Form" y al archivo nuevo lo nombramos como "LibroFrom")

**Comment by NicoBalbuena** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
integrado a develop.

**Comment by Ventc** [comment]
El desarrollador no realizó su ticket y se asignó a otro.

**Comment by Renzo-Espinola** [comment]
integrado a develop.
