### ISSUE TITLE
JAVA-Constructor para la inyección de dependencias de Spring

### ISSUE THREAD

**Issue by Ventc** [CodeSystem2022/ChacoDevsTeam-4SEM#183]
VIDEO 7 = (Se requiere crear un atributo llamado "LibroServicio" en la clase "LibroFrom")

**Comment by NicoBalbuena** [comment]
Se comienza desarrollo

**Comment by Ventc** [comment]
El desarrollador no realizó su ticket y se asignó a otro.

**Comment by Renzo-Espinola** [comment]
integrado a develop.
