### ISSUE TITLE
JS STACKPERN-Autenticación de usuarios

### ISSUE THREAD

**Issue by DiosJuanVero2015** [CodeSystem2022/ChacoDevsTeam-4SEM#197]
Se requiere Autenticacion de Usuario Video 1

**Comment by Renzo-Espinola** [comment]
se realiza el analisis del requerimiento

**Comment by Renzo-Espinola** [comment]
se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado a develop

**Comment by DiosJuanVero2015** [comment]
Se realizo Test, todo funciona correctamente.
