### ISSUE TITLE
Java-Clase SistemaEstudiantesApp

### ISSUE THREAD

**Issue by JuanValladaresv2** [CodeSystem2022/ChacoDevsTeam-4SEM#2]
CREAR EL MAIN CON EL NOMBRE SistemaEstudiantesApp DENTRO DEL PAQUETE presentación(Video 4)

**Comment by patiky** [comment]
comenzando desarrollo

**Comment by Renzo-Espinola** [comment]
Integrado a develop

**Comment by JuanValladaresv2** [comment]
Prueba realizada con éxito. Se cierra el ticket.
