### ISSUE TITLE
JS STACKPERN-Crear TOKEN

### ISSUE THREAD

**Issue by DiosJuanVero2015** [CodeSystem2022/ChacoDevsTeam-4SEM#200]
Se requiere la creación de un TOKEN (Video 5 y 6)

**Comment by ludmilailenrss** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado a develop.

**Comment by DiosJuanVero2015** [comment]
Se realizo Test, todo funciona correctamente
