### ISSUE TITLE
JS STACKPERN-Guardar TOKEN

### ISSUE THREAD

**Issue by DiosJuanVero2015** [CodeSystem2022/ChacoDevsTeam-4SEM#201]
Se requiere Guardar TOKEN en una Cookies (Video 7)

**Comment by AlejoHGZ** [comment]
se inicia desarrollo

**Comment by Renzo-Espinola** [comment]
Integrado a develop

**Comment by DiosJuanVero2015** [comment]
Se realizo Test, todo funciona correctamente
