### ISSUE TITLE
JAVA- Crear un componente

### ISSUE THREAD

**Issue by DiosJuanVero2015** [CodeSystem2022/ChacoDevsTeam-4SEM#209]
Se requiere crear un componente de Tipo Tabla (Video 4)

**Comment by AlejoHGZ** [comment]
se inicia el desarrollo

**Comment by Renzo-Espinola** [comment]
integrado a develop

**Comment by DiosJuanVero2015** [comment]
Se realizo Test, todo funciona correctamente
