### ISSUE TITLE
JAVA- Crear Modelo de Tabla

### ISSUE THREAD

**Issue by DiosJuanVero2015** [CodeSystem2022/ChacoDevsTeam-4SEM#210]
Se requiere rellenar la tabla con modelo creado (Video 5)

**Comment by naty33** [comment]
Se inicia desarrollo

**Comment by Renzo-Espinola** [comment]
integrado a develop

**Comment by DiosJuanVero2015** [comment]
Se realizo Test, todo funciona correctamente
