### ISSUE TITLE
JS-StackPern-Inicio de Sesión->Signin

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/ChacoDevsTeam-4SEM#221]
Crear una constante signing que busque el email dentro de usuarios(Video 1)

**Comment by TatianaGimenezRios** [comment]
Se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado a develop

**Comment by Renzo-Espinola** [comment]
Se realizaron las pruebas y fueron exitosas
