### ISSUE TITLE
JS-StackPern-Cierre de Sesion->Signout

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/ChacoDevsTeam-4SEM#222]
Eliminar la cookies creada al inicio-token y luego modificr el profile(Video 2)

**Comment by Ventc** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado a develop

**Comment by Renzo-Espinola** [comment]
Se realizaron las pruebas y fueron exitosas
