### ISSUE TITLE
JS-StackPern-Configuracion de frontend

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/ChacoDevsTeam-4SEM#224]
Creamos una carpeta desde Vite-junto a su dependencia. Seleccionamos React y Js. 
Luego creamos las rutas.(video 4)

**Comment by Renzo-Espinola** [comment]
integrado a develop

**Comment by Renzo-Espinola** [comment]
Se realizaron las pruebas y fueron exitosas
