### ISSUE TITLE
JS-StackPern-Formulario de Registro 1

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/ChacoDevsTeam-4SEM#225]
Dentro de la carpeta de frontend en registro, ingresamos un form con los diferentes input- nombre, apellido, email-.(video 5)

**Comment by ludmilailenrss** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado a develop

**Comment by Renzo-Espinola** [comment]
Se realizaron las pruebas y fueron exitosas
