### ISSUE TITLE
JS-StackPern-Formulario de registro 2

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/ChacoDevsTeam-4SEM#226]
Se solicita crear nuevo archivo index.js, el cual va a exportar una carpeta determinada desde la carpeta con el mismo nombre. Luego se importa en registerPage, para cambiar a una visual mejor al formulario.(video 6)

**Comment by Federico65744** [comment]
Se comienza el desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado a develop

**Comment by Renzo-Espinola** [comment]
Se realizaron las pruebas y fueron exitosas
