### ISSUE TITLE
JAVA-Armando la grafica Swing-JLabel y JTextField

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/ChacoDevsTeam-4SEM#227]
Dentro del formulario, se agregan 2 paneles-uno dentro del otro- del lado izquierdo, Se agregan JLabel y luego JTextField tambien dentro del panel izquierdo.(Video 1)

**Comment by Renzo-Espinola** [comment]
Se comienza con el desarrollo

**Comment by Renzo-Espinola** [comment]
integrado a develop

**Comment by Renzo-Espinola** [comment]
Se realizaron las pruebas y fueron exitosas
