### ISSUE TITLE
JAVA-Se incorpora boton agregar

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/ChacoDevsTeam-4SEM#228]
Se agregan separadores laterales al fomulario, luego incorporamos un JButton con el nombre agregar.(video 2)

**Comment by NicoBalbuena** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
Integrado a develop

**Comment by Renzo-Espinola** [comment]
Se realizaron las pruebas y fueron exitosas
