### ISSUE TITLE
JAVA Agregamos boton modificar y eliminar

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/ChacoDevsTeam-4SEM#229]
Agregar botones al formulario con JButton- con el nombre de modificar y otro eliminar. Luego se ajustan los formatos de la visual en el formulario(Video 3)

**Comment by TatianaGimenezRios** [comment]
Se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado a develop.

**Comment by Renzo-Espinola** [comment]
Se realizaron las pruebas y fueron exitosas
