### ISSUE TITLE
NODE- Presentacion de un callback real

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/ChacoDevsTeam-4SEM#236]
Añadimos la funcion hablar, varias veces para leer como si fuera una conversación. Luego se despide con un adios. (video 2)

**Comment by Renzo-Espinola** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
se integra a dev.

**Comment by naty33** [comment]
Se realizaron las pruebas y fueron exitosas
