### ISSUE TITLE
NODE- Acudimos a la recursividad

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/ChacoDevsTeam-4SEM#238]
Para definir la cantidad de veces en una conversacion, si es mayo de cero agregamos parametros de nomvre, veces y callback.
(video 4)

**Comment by Ventc** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado a develop

**Comment by naty33** [comment]
Se realizaron las pruebas y fueron exitosas
