### ISSUE TITLE
NODE-Llamamos a la funcion y hacemos la prueba

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/ChacoDevsTeam-4SEM#239]
Modificamos el llamado, escribimos functio(nombre) llamamos a conversación(Inombre, y cantidad de veces).
Luego agregamos el console.log("terminando el proceso").(Video 5)

**Comment by Ventc** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado develop.

**Comment by naty33** [comment]
Se realizaron las pruebas y fueron exitosas
