### ISSUE TITLE
NODE- Creamos la carpeta, archivo y código

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/ChacoDevsTeam-4SEM#241]
Comenzamos creando la carpeta 02_fundamentos_node, luego dentro de la misma una carpeta llamada async y una conceptos.
Dentro de la carpeta async un archivo llamado callback. Continúa con la creación de una función.(video 1)

**Comment by NicoBalbuena** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
integrado a develop

**Comment by naty33** [comment]
Se realizaron las pruebas y fueron exitosas
