### ISSUE TITLE
NODE-Creamos asincronía con el setTimeout

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/ChacoDevsTeam-4SEM#242]
Se crea una real sincronía con el setTimeout dentro de la función. Esto se genera junto a otra función estableciendo el tiempo en este caso de 1000milisegundos.(video 2)

**Comment by NicoBalbuena** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
Integrado a develop.
