### ISSUE TITLE
NODE- Generamos un callback

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/ChacoDevsTeam-4SEM#243]
Dentro de la función -soy asincronica- cargamos una función callbacky la llamamos para que de esa manera se realice la sincronía.(video 3)

**Comment by Federico65744** [comment]
Se comienza el desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado a develop

**Comment by naty33** [comment]
Se realizaron las pruebas y fueron exitosas
