### ISSUE TITLE
NODE-Hacemos cambios hacía un algoritmo más complejo .

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/ChacoDevsTeam-4SEM#244]
Cambiar nombre a la función y establecer 2 parámetros.(video 4)

**Comment by Federico65744** [comment]
Se comienza el desarrollo.

**Comment by naty33** [comment]
integrado a develop

**Comment by naty33** [comment]
Se realizaron las pruebas y fueron exitosas
