### ISSUE TITLE
NODE- Creacion de funciones definidas al principio#237

### ISSUE THREAD

**Issue by naty33** [CodeSystem2022/ChacoDevsTeam-4SEM#260]
Comenzamos con el hola hasta el adios, dejamos como comentario todo lo definido anteriormentge.
Realizamos una funcion, que se llame conversación, agregamos nombre, y veces con un callback)
(video 3)

**Comment by DiosJuanVero2015** [comment]
Se inicia Desarrollo

**Comment by Renzo-Espinola** [comment]
integrado a develop

**Comment by naty33** [comment]
Se realizaron las pruebas y fueron exitosas
