### ISSUE TITLE
JAVA SPRINGBOOT-Proyecto Tienda de Libros con SpringBoot y Swing-Acción al seleccionar la tabla

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/ChacoDevsTeam-4SEM#268]
Se requiere agregar un listener a la tabla del formulario, crear metodo cargarLibroSeleccionado()-VIDEO 1.
Crear variable renglon el cual guardara el ID renglon seleccionado, ademas una nueva variable de clase idTexto del tipo JTextField()-VIDEO 2

**Comment by TatianaGimenezRios** [comment]
Se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
Integrado a develop.

**Comment by Renzo-Espinola** [comment]
Se comienza con el testing

**Comment by Renzo-Espinola** [comment]
Las pruebas fueron exitossas, se procede a cerrar esta incidencia.

![Image](https://github.com/CodeSystem2022/ChacoDevsTeam-4SEM/assets/70241433/93a29bb6-c31d-4f4b-b967-e94a29fde4a3)
