### ISSUE TITLE
JAVA SPRINGBOOT-Proyecto Tienda de Libros con SpringBoot y Swing-Continuamos con la carga del libro seleccionado y boton modificar

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/ChacoDevsTeam-4SEM#269]
Completar el metodo cargarLibroSeleccionado con todos los campos del libro VALIDAR QUE SE COMPLETEN LOS CAMPOS DE LIBRO CUANDO SE SELECCIONE UNA FILA DE LA TABLA - VIDEO 3
Se requiere agregar listener al boton modificar, crear metodo modificarLibro - VIDEO 4

**Comment by Renzo-Espinola** [comment]
Se puede proseguir

**Comment by patiky** [comment]
iniciando el desarrollo

**Comment by patiky** [comment]
desarrollo finalizado

**Comment by Renzo-Espinola** [comment]
Integrado a develop

**Comment by Renzo-Espinola** [comment]
Se comienza con el testing

**Comment by Renzo-Espinola** [comment]
Las pruebas fueron exitosas, se procede a cerrar esta incidencia.


![Image](https://github.com/CodeSystem2022/ChacoDevsTeam-4SEM/assets/70241433/eca949a1-e323-418d-94a4-7eb2754ba534)
