### ISSUE TITLE
JAVA SPRINGBOOT-Proyecto Tienda de Libros con SpringBoot y Swing-Pruebas y Desactivar caracteristicas

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/ChacoDevsTeam-4SEM#273]
Se requiere realizar pruebas del funcionamiento tal como se hace en el VIDEO 7
Se debe desactivar la modificaciones en la tabla metodo createUIComponents VIDEO 8
Se debe desactivar la seleccion multiple de la tabla VIDEO 9

Se requiere esperar a la finalizacion del ticket #272

**Comment by Renzo-Espinola** [comment]
Se puede comenzar con el desarrollo

**Comment by AlejoHGZ** [comment]
se inicia el desarrollo

**Comment by Renzo-Espinola** [comment]
Se integra a develop

**Comment by Renzo-Espinola** [comment]
Se comienza con el testing

**Comment by Renzo-Espinola** [comment]
Las pruebas fueron exitosas, la tabla no permitio que se seleccionaran mas de una fila, se procede a cerrar esta incidencia.
