### ISSUE TITLE
NODE-Promises - Resolve reject -  Introducción a las promesas

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/ChacoDevsTeam-4SEM#274]
Se requiere crear un archivo js con el nombre promises.js, copiar las funciones  hola, hablar y adios VIDEO 1

**Comment by NicoBalbuena** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
integrado a develop

**Comment by Renzo-Espinola** [comment]
Se comienza con el testing

**Comment by Renzo-Espinola** [comment]
Las pruebas fueron satisfactorias.
