### ISSUE TITLE
NODE-Promises - Resolve reject - Aplicando Promise en la función hola

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/ChacoDevsTeam-4SEM#275]
Se requiere modificar la funcion hola y generar el llamado a esta funcion pasandole un argumento VIDEO 2

Se debe esperar a la finalizacion del ticket #274

**Comment by Renzo-Espinola** [comment]
Se puede proseguir

**Comment by ludmilailenrss** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado a develop

**Comment by Renzo-Espinola** [comment]
Se comienza con el testing

**Comment by Renzo-Espinola** [comment]
Las pruebas fueron satisfactorias.
