### ISSUE TITLE
NODE-Promises - Resolve reject - Aplicando Promise en la función adios

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/ChacoDevsTeam-4SEM#276]
Se requiere modificar la funcion adios, dentro del llamado a la funcion hola de debe agregar un nuevo then VIDEO 3

Se debe esperar por la finalizacion del ticket #275

**Comment by Renzo-Espinola** [comment]
Se puede comenzar con el desarrollo

**Comment by naty33** [comment]
Se comienza el desarrollo

**Comment by Renzo-Espinola** [comment]
Integrado a develop

**Comment by Renzo-Espinola** [comment]
Se comienza con el testing

**Comment by Renzo-Espinola** [comment]
Las pruebas fueron satisfactorias
