### ISSUE TITLE
NODE-Promises - Resolve reject - Aplicando Promise en la función hablar

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/ChacoDevsTeam-4SEM#277]
Se requiere modificar la funcion hablar,  se debe agregar un then al llamado de la funcion hola VIDEO 4

Se debe esperar por la finalizacion del ticket #276

**Comment by Renzo-Espinola** [comment]
Se puede iniciar el desarrollo

**Comment by Federico65744** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado a develop.

**Comment by Renzo-Espinola** [comment]
Se comienza con el testing

**Comment by Renzo-Espinola** [comment]
Las pruebas fueron satisfactorias
