### ISSUE TITLE
NODE-Promises - Resolve reject - Utilizamos reject con el .catch

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/ChacoDevsTeam-4SEM#278]
Se requiere modificar la funcion adios agregando un reject, agregar catch al llamado de la funcion hola.

Se debe esperar a la finalizacion del ticket #277

**Comment by Renzo-Espinola** [comment]
Se puede comenzar con el desarrollo

**Comment by DiosJuanVero2015** [comment]
Se inicia desarrollo

**Comment by Renzo-Espinola** [comment]
integrado a develop.

**Comment by Renzo-Espinola** [comment]
Se comienza con el testing

**Comment by Renzo-Espinola** [comment]
Las pruebas fueron satisfactorias.


![Image](https://github.com/CodeSystem2022/ChacoDevsTeam-4SEM/assets/70241433/558f9194-1bd3-475d-aaa7-fc1e767c3ec4)
