### ISSUE TITLE
Java- Método mostrarMenu

### ISSUE THREAD

**Issue by JuanValladaresv2** [CodeSystem2022/ChacoDevsTeam-4SEM#3]
CREAR MÉTODO mostrarMenu en el que se mostraran las posibles opciones a digitar par el usuario(Video 5, depende del ticket #2)

**Comment by DiosJuanVero2015** [comment]
Se inicia desarrollo

**Comment by Renzo-Espinola** [comment]
Integrado a develop

**Comment by JuanValladaresv2** [comment]
Prueba realizada con éxito. Se cierra el ticket.
