### ISSUE TITLE
PYTHON - Configurar .gitignore y readme.md

### ISSUE THREAD

**Issue by JuanValladaresv2** [CodeSystem2022/ChacoDevsTeam-4SEM#309]
Crear el archivo gitignore y traer el codigo desde la pagina gitignore.io. Y luego crear el archivo readme.md (VIDEO 1)

**Comment by Renzo-Espinola** [comment]
se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
FInalizado el desarrollo integrado a develop
