### ISSUE TITLE
NODE-Módulos -> File System - Leer archivos -> utilizamos la sintaxis de ES6

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/ChacoDevsTeam-4SEM#332]
Se requiere  crear la funcion leer() en el archivo fs.js, llamar a la funcion leer() con el path del archivo.txt agregar console.log (VIDEO 2)

**Comment by NicoBalbuena** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
se puede comenzar con el desarrollo
