### ISSUE TITLE
NODE-Módulos -> File System - Escribir y crear un archivo

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/ChacoDevsTeam-4SEM#333]
Se requiere crear la funcion escribir() en el archivo fs.js, se requiere que se pruebe la sobrescritura de un archivo.txt existente y la creacion de un archivo nuevo y guarde la informacion que se le pasa por argumento a la funcion (VIDEO 3)

**Comment by Renzo-Espinola** [comment]
Se puede iniciar el desarrollo

**Comment by patiky** [comment]
Iniciando el desarrollo

**Comment by patiky** [comment]
desarrollo finalizado

**Comment by Renzo-Espinola** [comment]
Integrado a develop
