### ISSUE TITLE
PYTHON - Entorno Profesional -> Parte 4 - Creacion carpeta app

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/ChacoDevsTeam-4SEM#335]
Se requiere agregar al proyecto py-project la carpeta app que el profe dejo en el campus para descargar (VIDEO 1).

![Image](https://github.com/CodeSystem2022/ChacoDevsTeam-4SEM/assets/70241433/41539a7d-43ae-4bf6-9581-a54aa0f88f07)

**Comment by Renzo-Espinola** [comment]
Se puede arrancar con el desarrollo

**Comment by Federico65744** [comment]
Se comienza el desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado a develop
