### ISSUE TITLE
PYTHON - Entorno Profesional -> Parte 4 - dependencias , archivos main y charts

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/ChacoDevsTeam-4SEM#336]
Se requiere instalar las dependencias necesarias (VIDEO 2).
Se requiere modificar el archivo charts y descomentar el codigo del arvhivo main (VIDEO 3)

**Comment by Renzo-Espinola** [comment]
Se puede iniciar el desarrollo

**Comment by JuanValladaresv2** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
Integrado a develop
