### ISSUE TITLE
PYTHON - Entorno Profesional -> Parte 4 - Ejecución -> análisis y errores

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/ChacoDevsTeam-4SEM#337]
Se requiere ejecutar el codigo y realizar las modificaciones correspondientes en el archivo main, realizar pruebas sobre diferentes paises (VIDEO 4).

**Comment by Renzo-Espinola** [comment]
Se puede comenzar con el desarrollo

**Comment by ludmilailenrss** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado a develop.
