### ISSUE TITLE
PYTHON - Entorno Profesional -> Parte 4 - mejoras y ajustes 1

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/ChacoDevsTeam-4SEM#338]
Se requiere realizar la mejora correspondiente para mostrar el nombre del pais en el archivo charts.py en la function generate_bar_char, ademas de modificar en la clase main el llamado a la function pasandole la variable country y utilizar el print para mostrar su valor. Realizar la prueba correspondiente (VIDEO 5)

**Comment by DiosJuanVero2015** [comment]
Se inicia desarrollo

**Comment by DiosJuanVero2015** [comment]
se finaliza desarrollo
