### ISSUE TITLE
PYTHON - Entorno Profesional -> Parte 4 - mejoras y ajustes 2

### ISSUE THREAD

**Issue by Renzo-Espinola** [CodeSystem2022/ChacoDevsTeam-4SEM#339]
Se requiere realizar la correccion correspondiente en "Country".
Se requiere crear la carpeta imgs.
Realizar las pruebas correspondientes con varios paises.

**Comment by Renzo-Espinola** [comment]
se pude comenzar con el desarrollo

**Comment by AlejoHGZ** [comment]
se inicia el desarrollo

**Comment by Renzo-Espinola** [comment]
El desarrollador @AlejoHGZ no realizo su asignacion. Procedo a terminar con el ticket

**Comment by Renzo-Espinola** [comment]
Se finaliza el ticket y se integra a develop
