### ISSUE TITLE
Node-Variables let y const

### ISSUE THREAD

**Issue by TatianaGimenezRios** [CodeSystem2022/ChacoDevsTeam-4SEM#34]
Crear la carpeta dentro del repositorio con el nombre NODE, dentro creamos la carpeta 01-Hola-Mundo, dentro de la misma se debe crear el archivo app.js donde se define una variable, asignarle un valor. 
Mostrar por consola. Asignarle otro valor a la misma variable y mostrar por consola.
Video 1

**Comment by naty33** [comment]
Se comiena desarrollo

**Comment by TatianaGimenezRios** [comment]
Las pruebas salieron bien. Se cierra incidencia.
