### ISSUE TITLE
Node-Hola mundo

### ISSUE THREAD

**Issue by TatianaGimenezRios** [CodeSystem2022/ChacoDevsTeam-4SEM#35]
Modificar el archivo app.js 
Cambiar la variable nombre por una constante.
Modificar la segunda variable para que no genere error.
Mostrar por consola "Hola Mundo desde Node"
Video 2

**Comment by naty33** [comment]
Se comienza desarrollo

**Comment by TatianaGimenezRios** [comment]
Las pruebas salieron bien. Se cierra incidencia.
