### ISSUE TITLE
JAVA-SPRINGBOOT-Creación proyecto estudiante

### ISSUE THREAD

**Issue by TatianaGimenezRios** [CodeSystem2022/ChacoDevsTeam-4SEM#36]
Se requiere crear un proyecto de springboot con maven para el proyecto estudiante, agregar dependencias: jpa, mysql driver, lombok, con Java 20. (Videos 1 y 2).

**Comment by patiky** [comment]
comenzando desarrollo

**Comment by TatianaGimenezRios** [comment]
Integrado a develop.

**Comment by TatianaGimenezRios** [comment]
Las pruebas salieron bien. Se cierra incidencia.
