### ISSUE TITLE
JAVA-SPRINGBOOT-Configuración application.properties

### ISSUE THREAD

**Issue by TatianaGimenezRios** [CodeSystem2022/ChacoDevsTeam-4SEM#37]
Se requiere configurar en el applicaction.properties la conexión con la base de datos estudiantes, realizar la configuración para desactivar tomcat nativo y agregar configuración para evitar que se cree el esquema nuevamente.
Agregar el archivo de configuración de logback.
(Videos 3,4,5y 6)

**Comment by NicoBalbuena** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
Integrado a develop

**Comment by TatianaGimenezRios** [comment]
Las pruebas salieron bien. Se cierra incidencia.
