### ISSUE TITLE
Java- Método ejecutarOpciones

### ISSUE THREAD

**Issue by JuanValladaresv2** [CodeSystem2022/ChacoDevsTeam-4SEM#4]
CREAR MÉTODO ejecutarOpciones con un condicional switch en el que se creen casos para listar, filtrar, agregar, modificar, y eliminar estudiantes de la base de datos(Video 6,7(Depende de ticket #2)

**Comment by TatianaGimenezRios** [comment]
Se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
Integrado a develop.

**Comment by JuanValladaresv2** [comment]
Prueba realizada con éxito. Se cierra el ticket.
