### ISSUE TITLE
PYTHON - Valor Infinito Positivo y negativo #45

### ISSUE THREAD

**Issue by patiky** [CodeSystem2022/ChacoDevsTeam-4SEM#45]
Definimos los Tipos de valores Infinitos  Positivo y negativo (Video 6 y 7)

**Comment by DiosJuanVero2015** [comment]
Se comienza desarrollo

**Comment by Renzo-Espinola** [comment]
integrado a develop.

**Comment by patiky** [comment]
Las pruebas fueron satisfactorias
