### ISSUE TITLE
JS- Código de botón de compra y Carrito #46

### ISSUE THREAD

**Issue by patiky** [CodeSystem2022/ChacoDevsTeam-4SEM#46]
crear el Código de botón de compra y revisar el codigo del carrito (Video 1 y 2)

**Comment by Ventc** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado a develop.

**Comment by patiky** [comment]
Las pruebas fueron satisfactorias

**Comment by Renzo-Espinola** [comment]
Las pruebas fueron satisfactorias.


![Image](https://github.com/CodeSystem2022/ChacoDevsTeam-4SEM/assets/70241433/efa7e18e-bc9a-4e01-ab77-5a50ca0b8589)

**Comment by Renzo-Espinola** [comment]
se cierra esta incidencia.
