### ISSUE TITLE
JS-Modal del carrito #47

### ISSUE THREAD

**Issue by patiky** [CodeSystem2022/ChacoDevsTeam-4SEM#47]
Crear el Modal del carrito en el header (Video 3 y 4)

**Comment by Renzo-Espinola** [comment]
integrado a develop.

**Comment by Renzo-Espinola** [comment]
Las pruebas fueron satisfactorias


![Image](https://github.com/CodeSystem2022/ChacoDevsTeam-4SEM/assets/70241433/45d18f62-3054-467d-a4bf-2be61f09c016)

**Comment by Renzo-Espinola** [comment]
se cierra esta incidencia.
