### ISSUE TITLE
Python- Clase Entidad usuario

### ISSUE THREAD

**Issue by JuanValladaresv2** [CodeSystem2022/ChacoDevsTeam-4SEM#5]
CREAR CLASE ENTIDAD Usuario, CARGAR SUS ATRIBUTOS id_usuario, username y password DE MANERA ENCAPSULADA CON SUS METODOS GET Y SET Y CREAR EL MÉTODO __str__ (Video 3)

**Comment by Renzo-Espinola** [comment]
Se comienza con el desarrollo

**Comment by Renzo-Espinola** [comment]
integrado.

**Comment by JuanValladaresv2** [comment]
Prueba realizada con éxito. Se cierra el ticket.
