### ISSUE TITLE
JAVA-Paquete Modelo - Entidad Estudiante #51

### ISSUE THREAD

**Issue by patiky** [CodeSystem2022/ChacoDevsTeam-4SEM#51]
Crear  paquete modelo y la clase entidad Estudiante ( Video 1, 2 y 3)

**Comment by AlejoHGZ** [comment]
se inicia desarrollo

**Comment by Renzo-Espinola** [comment]
integrado a develop.

**Comment by patiky** [comment]
Las pruebas fueron satisfactorias
