### ISSUE TITLE
BD- ACTIVIDAD SEMANA 3

### ISSUE THREAD

**Issue by patiky** [CodeSystem2022/ChacoDevsTeam-4SEM#58]
Actividades:

•1- Realizar el cuestionario para la asistencia en el campus
•2- En grupo crear un nuevo documento con el nombre página web que contenga los archivos columnas.html y columnas.css, añadir la etiqueta viewport y  el enlace a la hoja de style de nombre columnas.css como en el ejemplo. Realizar una 1 captura por grupo.
•3- Realizar 1 ejemplo de Encapsulación, Abstracción, Herencia y Polimorismo. Utilizar cualquier diagrama UML online para realizarlo.
•Enviar  trabajo en formato PDF o Word con el nombre del grupo y  alumnos que participaron.
•Fecha de entrega :15/09

**Comment by Renzo-Espinola** [comment]
Se comienza el desarrollo primera parte de HTML y CSS.

**Comment by patiky** [comment]
Las pruebas fueron satisfactorias
