### ISSUE TITLE
Python- Clase usuarioDAO

### ISSUE THREAD

**Issue by JuanValladaresv2** [CodeSystem2022/ChacoDevsTeam-4SEM#6]
CREAR CLASE usuario_dao Y CREAR LOS MÉTODOS DE CLASE PARA COMUNICARSE CON LA BASE DE DATOS(Video 4)

**Comment by Renzo-Espinola** [comment]
Integrado a develop

**Comment by DiosJuanVero2015** [comment]
Se inicia desarrollo

**Comment by AlejoHGZ** [comment]
Se inicia desarrollo

**Comment by JuanValladaresv2** [comment]
Prueba realizada con éxito. Se cierra el ticket.
