### ISSUE TITLE
Python- Testeo clase Usuario_DAO

### ISSUE THREAD

**Issue by JuanValladaresv2** [CodeSystem2022/ChacoDevsTeam-4SEM#7]
REALIZAR PRUEBAS EN LA CLASE usuario_dao PARA VERIFICAR SU FUNCIONAMIENTO(Video 6, depende de ticket #6 )

**Comment by Ventc** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
se integra a develop.

**Comment by JuanValladaresv2** [comment]
Prueba realizada con éxito. Se cierra el ticket.
