### ISSUE TITLE
JAVA-Nuevo metodo

### ISSUE THREAD

**Issue by NicoBalbuena** [CodeSystem2022/ChacoDevsTeam-4SEM#74]
Se requiere crear metodos listarEstudiante y buscarEstudiantePorId (video 1 y 2)

**Comment by NicoBalbuena** [comment]
Se requiere crear metodos  listarEstudiante y buscarEstudiantePorId (video 1 y 2)

**Comment by Federico65744** [comment]
Se comienza el desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado a develop.

**Comment by NicoBalbuena** [comment]
Se testea ok.
