### ISSUE TITLE
JAVA-Nuevos Metedos 2da parte

### ISSUE THREAD

**Issue by NicoBalbuena** [CodeSystem2022/ChacoDevsTeam-4SEM#75]
(VIDEOS 3 Y 4  )       Se requiere crear el método guardarEstudiante y eliminarEstudiante y luego comenzar con la capa de presentación 
                                 donde se la implementación de CommandLineRunner

**Comment by AlejoHGZ** [comment]
se inicia el desarrollo

**Comment by Renzo-Espinola** [comment]
integrado a develop.

**Comment by NicoBalbuena** [comment]
Se testea ok.
