### ISSUE TITLE
Python- Archivo menu_app_usuario

### ISSUE THREAD

**Issue by JuanValladaresv2** [CodeSystem2022/ChacoDevsTeam-4SEM#8]
CREAR EL ARCHIVO menu_app_usuario DONDE SE CREARA EL MENU ENVUELTO EN UN CICLO WHILE(Video 6)

**Comment by Ventc** [comment]
Se comienza desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado a develop

**Comment by JuanValladaresv2** [comment]
Prueba realizada con éxito. Se cierra el ticket.
