### ISSUE TITLE
JAVASCRIPT-Suma y Resta

### ISSUE THREAD

**Issue by NicoBalbuena** [CodeSystem2022/ChacoDevsTeam-4SEM#81]
Se requiere configurar los productos y agregar botones de suma y resta(video 3 y 4)

**Comment by TatianaGimenezRios** [comment]
Se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
integrado a develop.

**Comment by NicoBalbuena** [comment]
Se testea ok.
