### ISSUE TITLE
Python- Comprobaciones para el menu_app_usuario

### ISSUE THREAD

**Issue by JuanValladaresv2** [CodeSystem2022/ChacoDevsTeam-4SEM#9]
CREAR COMPROBACIONES PARA LAS DIFERENTES OPCIONES DEL MENU(Videos 7, 8, 9(Depende de ticket #8))

**Comment by TatianaGimenezRios** [comment]
Se inicia desarrollo.

**Comment by Renzo-Espinola** [comment]
Integrado a develop.

**Comment by JuanValladaresv2** [comment]
Prueba realizada con éxito. Se cierra el ticket.
